/** Tailwind equivalents for the semantic classes used by component CSS. */
export const styleClassMap: Record<string, string> = {
  accordion: 'w-full max-w-[calc(var(--manti-space-16)*7)]',
  'alert-list': 'grid gap-3 w-full',
  'avatar-group': 'flex gap-4 items-center',
  calendar: 'flex flex-col gap-5',
  'calendar-toolbar': 'flex items-center justify-between gap-4',
  'calendar-heading': 'm-0',
  'calendar-actions': 'flex items-center gap-3',
  'card-panel-wide': 'w-full max-w-[calc(var(--manti-space-16)*8)]',
  'card-header': 'flex justify-between items-center',
  'card-panel': 'w-full max-w-[calc(var(--manti-space-16)*5)]',
  'carousel-slide-featured':
    'grid place-items-center h-[calc(var(--manti-space-16)*3)] rounded-lg bg-surface-raised text-xl font-semibold',
  carousel: 'w-full max-w-[calc(var(--manti-space-16)*9)]',
  'carousel-slide':
    'grid place-items-center h-[calc(var(--manti-space-16)*3)] rounded-lg bg-surface-raised text-lg font-semibold',
  'checkbox-group': 'grid gap-3',
  'checkbox-row': 'flex gap-6 items-center',
  'clipboard-field': 'w-full max-w-[calc(var(--manti-space-16)*6)]',
  collapsible: 'w-full max-w-[calc(var(--manti-space-16)*6)]',
  'collapsible-note': 'p-3 px-1 pt-3',
  'combobox-field': 'w-full max-w-[calc(var(--manti-space-16)*5)]',
  'combobox-stack':
    'flex flex-col gap-4 w-full max-w-[calc(var(--manti-space-16)*5)]',
  'combobox-grid': 'grid gap-4 w-full max-w-[calc(var(--manti-space-16)*5)]',
  'context-menu-target':
    'grid place-items-center w-[calc(var(--manti-space-16)*5)] h-[calc(var(--manti-space-16)*2.75)] rounded-lg border border-border border-dashed border-border-strong text-text-muted text-sm select-none',
  'data-table-stack': 'flex flex-col gap-6 w-full',
  'drawer-grid': 'grid gap-4',
  'drawer-options': 'flex flex-wrap gap-3',
  'file-upload': 'w-full max-w-[calc(var(--manti-space-16)*6)]',
  'hover-card-content': 'grid gap-1',
  'input-field-wide': 'w-full max-w-[calc(var(--manti-space-16)*6)]',
  'input-pair-grid': 'grid gap-4 w-full max-w-[calc(var(--manti-space-16)*6)]',
  'input-field': 'w-full max-w-[calc(var(--manti-space-16)*5)]',
  'input-state-grid': 'grid gap-4 w-full max-w-[calc(var(--manti-space-16)*6)]',
  'input-option-grid':
    'grid gap-4 w-full max-w-[calc(var(--manti-space-16)*6)]',
  'listbox-options': 'flex gap-4 flex-wrap',
  'marquee-grid': 'grid gap-6',
  'menu-options': 'flex gap-3',
  'number-input-options': 'grid gap-4',
  'pagination-options': 'flex flex-col gap-4 items-start',
  'pin-input-options': 'flex flex-col gap-4 items-start',
  'popover-options': 'flex flex-wrap justify-center gap-3',
  progress: 'w-full max-w-[calc(var(--manti-space-16)*8)]',
  'progress-stack':
    'flex flex-col gap-5 w-full max-w-[calc(var(--manti-space-16)*8)]',
  'rating-group-options': 'flex flex-col gap-4 items-start',
  'scroll-area':
    'h-[calc(var(--manti-space-16)*3.25)] w-full max-w-[calc(var(--manti-space-16)*6)] border border-border rounded-md bg-surface',
  'scroll-area-content':
    'grid gap-3 p-4 text-text-muted text-sm leading-normal',
  'scroll-area-horizontal':
    'w-full max-w-[calc(var(--manti-space-16)*6)] border border-border rounded-md bg-surface',
  'scroll-area-row': 'flex gap-2 p-3',
  'segmented-control-options': 'flex flex-col gap-4 items-start',
  'select-field': 'w-full max-w-[calc(var(--manti-space-16)*5)]',
  'select-stack':
    'flex flex-col gap-4 w-full max-w-[calc(var(--manti-space-16)*5)]',
  'select-grid': 'grid gap-4 w-full max-w-[calc(var(--manti-space-16)*5)]',
  'shortcut-grid': 'grid gap-3 w-[calc(var(--manti-space-16)*4)]',
  'shortcut-status': 'flex items-center gap-3',
  'shortcut-key': 'font-mono',
  'shortcut-list': 'flex gap-2 flex-wrap',
  'shortcut-log': 'grid gap-1 p-4 min-h-[calc(var(--manti-space-16)*1.5)]',
  'shortcut-empty': 'text-text-muted',
  'shortcut-entry': 'font-mono',
  'shortcut-entry-muted': 'font-mono text-text-subtle',
  'shortcut-scope': 'outline-none',
  'shortcut-panel': 'grid gap-3 p-5 w-[calc(var(--manti-space-16)*4)]',
  'signature-pad': 'w-full max-w-[calc(var(--manti-space-16)*6)]',
  'slider-field': 'w-full max-w-[calc(var(--manti-space-16)*6)]',
  'slider-range': 'grid gap-6 w-full max-w-[calc(var(--manti-space-16)*6)]',
  'splitter-pane':
    'grid place-items-center h-[calc(var(--manti-space-16)*3)] text-text-muted',
  splitter: 'w-full',
  'steps-field': 'w-full',
  tabs: 'w-full max-w-[calc(var(--manti-space-16)*8)]',
  'tabs-stack':
    'flex flex-col gap-6 w-full max-w-[calc(var(--manti-space-16)*8)]',
  'tags-input': 'w-full max-w-[calc(var(--manti-space-16)*7)]',
  'tags-input-grid': 'grid gap-4 w-full max-w-[calc(var(--manti-space-16)*7)]',
  'textarea-field': 'w-full max-w-[calc(var(--manti-space-16)*6)]',
  'textarea-grid': 'grid gap-4 w-full max-w-[calc(var(--manti-space-16)*6)]',
  'toast-actions': 'flex flex-wrap gap-2 justify-center',
  'toggle-actions': 'flex gap-3 items-center',
  'toggle-status': 'text-text-muted',
  'toggle-group-options': 'flex flex-col gap-4 items-start',
  'blockquote-list': 'grid gap-6 max-w-[calc(var(--manti-space-16)*10)]',
  'heading-list': 'grid gap-4',
  'heading-list-wide': 'grid gap-2 max-w-[calc(var(--manti-space-16)*10)]',
  'kbd-list': 'flex items-center gap-4',
  'kbd-item': 'inline-flex items-center gap-2',
  'text-list': 'grid gap-3',
  'text-block': 'max-w-[calc(var(--manti-space-16)*5)]',
};
